name: mobile_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  json_annotation: ^4.8.0
  lottie: ^2.3.0
  url_launcher: ^6.1.10
  vexana: ^3.3.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  flutter_native_splash: ^2.2.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
